---
- name: "Configure SSL Certificates"
  hosts: "localhost"
  connection: "local"
  vars_files:
    - '{{ "site_" + deployment_site + ".yml" }}'

  tasks:
    - name: "Create RC-LAB-CA Certificate"
      vmware.alb.avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "RC-LAB-CA"
        type: "SSL_CERTIFICATE_TYPE_CA"
        certificate:
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIB/zCCAaWgAwIBAgIQYUcGIH8S175HYqlfsZj4uzAKBggqhkjOPQQDAjBYMRgw
            FgYKCZImiZPyLGQBGRYIaW50ZXJuYWwxFDASBgoJkiaJk/IsZAEZFgRkZW1vMRIw
            EAYKCZImiZPyLGQBGRYCcmMxEjAQBgNVBAMTCVJDLUxBQi1DQTAeFw0yNDEwMTkw
            MDA3MzVaFw0zNDEwMTkwMDE3MzVaMFgxGDAWBgoJkiaJk/IsZAEZFghpbnRlcm5h
            bDEUMBIGCgmSJomT8ixkARkWBGRlbW8xEjAQBgoJkiaJk/IsZAEZFgJyYzESMBAG
            A1UEAxMJUkMtTEFCLUNBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2coDhtNF
            7Gb9dDRLv2aMiSTy/5tz9ACmCDfAZAajtGJ9SwrbcSArrJ5ZVeDERiT5DysRk1IG
            Zxjw45ZcyLYyD6NRME8wCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHQYD
            VR0OBBYEFJBUB37lU+Y0CD5d+Nm2lN+tGSfbMBAGCSsGAQQBgjcVAQQDAgEAMAoG
            CCqGSM49BAMCA0gAMEUCIQDzIvATDDcmvNUwviNlWQuKDH4+v3D+BBXSPY7gDInc
            rgIgXo9OlJQc7xOmP3Qud5yKTKbTOSiVTtumaUuBVAZC+Yc=
            -----END CERTIFICATE-----
        key_params:
          algorithm: "SSL_KEY_ALGORITHM_EC"
          ec_params:
            curve: "SSL_KEY_EC_CURVE_SECP256R1"
        format: SSL_PEM

    - name: "Create Wildcard-ECDSA-Cert"
      vmware.alb.avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "Wildcard-ECDSA-Cert"
        type: "SSL_CERTIFICATE_TYPE_VIRTUALSERVICE"
        certificate:
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIFATCCBKegAwIBAgITGAAAAAlCf7Zp/imyXgAAAAAACTAKBggqhkjOPQQDAjBY
            MRgwFgYKCZImiZPyLGQBGRYIaW50ZXJuYWwxFDASBgoJkiaJk/IsZAEZFgRkZW1v
            MRIwEAYKCZImiZPyLGQBGRYCcmMxEjAQBgNVBAMTCVJDLUxBQi1DQTAeFw0yNDEw
            MjExODAyNDBaFw0yNjEwMjExODAyNDBaMD4xCzAJBgNVBAYTAkdCMQ8wDQYDVQQK
            EwZSQ0RFTU8xHjAcBgNVBAMMFSoudnMucmMuZGVtby5pbnRlcm5hbDB2MBAGByqG
            SM49AgEGBSuBBAAiA2IABIkUN0nnZi7jrjlcvzL0MRtwpQwob3tc06G8+KozGSpd
            cVGVd1KDaUQ6yu+tmOiwNnGyJjhUpviOk0ZaHCoPpRya1AXcMyZLeSjxyHQ/LfTW
            RkTAGCQdgB3lOLRp2URoz6OCA0swggNHMIHmBgNVHREEgd4wgduCFSoudnMucmMu
            ZGVtby5pbnRlcm5hbIIWKi52czIucmMuZGVtby5pbnRlcm5hbIIWKi52czMucmMu
            ZGVtby5pbnRlcm5hbIIWKi52czQucmMuZGVtby5pbnRlcm5hbIIWKi52czUucmMu
            ZGVtby5pbnRlcm5hbIIXKi5nc2xiLnJjLmRlbW8uaW50ZXJuYWyCFiouYWtvLnJj
            LmRlbW8uaW50ZXJuYWyCFyouYWtvMi5yYy5kZW1vLmludGVybmFsghgqLmdzbGIy
            LnJjLmRlbW8uaW50ZXJuYWwwHQYDVR0OBBYEFIQV1sZA7/IZ3z883ENqh+ifKiOG
            MB8GA1UdIwQYMBaAFJBUB37lU+Y0CD5d+Nm2lN+tGSfbMIHUBgNVHR8Egcwwgckw
            gcaggcOggcCGgb1sZGFwOi8vL0NOPVJDLUxBQi1DQSxDTj1yYy13aW5zZXJ2ZXIs
            Q049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENO
            PUNvbmZpZ3VyYXRpb24sREM9cmMsREM9ZGVtbyxEQz1pbnRlcm5hbD9jZXJ0aWZp
            Y2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0
            aW9uUG9pbnQwgcMGCCsGAQUFBwEBBIG2MIGzMIGwBggrBgEFBQcwAoaBo2xkYXA6
            Ly8vQ049UkMtTEFCLUNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNl
            cyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPXJjLERDPWRlbW8sREM9
            aW50ZXJuYWw/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmlj
            YXRpb25BdXRob3JpdHkwDgYDVR0PAQH/BAQDAgeAMD0GCSsGAQQBgjcVBwQwMC4G
            JisGAQQBgjcVCIT+omSHs+kdhrWFLYHV9T6Dnd5RRYfd4hCHyJZyAgFkAgEEMBMG
            A1UdJQQMMAoGCCsGAQUFBwMBMBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYBBQUHAwEw
            CgYIKoZIzj0EAwIDSAAwRQIgDV+BQEjoeniS7D0R5zjFnzeXgGH4GleqZ9wZmRId
            TaECIQDN5JJj5wqKzB9aWWfcqDnUTGLO6YX8JcOgomMvSJcD8Q==
            -----END CERTIFICATE-----
        key_params:
          algorithm: "SSL_KEY_ALGORITHM_EC"
          ec_params:
            curve: "SSL_KEY_EC_CURVE_SECP256R1"
        key: |
          -----BEGIN EC PRIVATE KEY-----
          MIGkAgEBBDBMiVBpQvizPxnYudJq10B9TMKnHemYhynkfK6rPieWE1RWuKfpPulI
          9hfKIdrHnJegBwYFK4EEACKhZANiAASJFDdJ52Yu4645XL8y9DEbcKUMKG97XNOh
          vPiqMxkqXXFRlXdSg2lEOsrvrZjosDZxsiY4VKb4jpNGWhwqD6UcmtQF3DMmS3ko
          8ch0Py301kZEwBgkHYAd5Ti0adlEaM8=
          -----END EC PRIVATE KEY-----
        format: SSL_PEM

    - name: "Create Wildcard-RSA-Cert"
      vmware.alb.avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "Wildcard-RSA-Cert"
        type: "SSL_CERTIFICATE_TYPE_VIRTUALSERVICE"
        certificate:
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIFsDCCBVWgAwIBAgITGAAAAApdxgCQDOhIlgAAAAAACjAKBggqhkjOPQQDAjBY
            MRgwFgYKCZImiZPyLGQBGRYIaW50ZXJuYWwxFDASBgoJkiaJk/IsZAEZFgRkZW1v
            MRIwEAYKCZImiZPyLGQBGRYCcmMxEjAQBgNVBAMTCVJDLUxBQi1DQTAeFw0yNDEw
            MjExODA0NTdaFw0yNjEwMjExODA0NTdaMD4xCzAJBgNVBAYTAkdCMQ8wDQYDVQQK
            EwZSQ0RFTU8xHjAcBgNVBAMMFSoudnMucmMuZGVtby5pbnRlcm5hbDCCASIwDQYJ
            KoZIhvcNAQEBBQADggEPADCCAQoCggEBAKmvHiWYrgZxfI0U2huVQhwtjR5rj4qY
            OKxttdztwT4NOVtaev3e0oMo7IP3d49JI236ntfhhpqmGOQGwHmn5nAzU4WVQcwF
            2sCrRbAcJiKAgKOamM5u4SnUlkaZhiWRb4f7Ryr0UdvI2MfodyIF+XvAHsyXD9LN
            cLvhRrORumKxF/gIFYA8D21Ez7EV/Qe85RFEzVHb5mHneoQAFLjkNwhv2j3PWai0
            xcTdfrGF0N6e9jz11Ga8SuPPR6P6+m7UsU7ojSct8F7fYvk/3Cd4BalRRUUjOhy7
            favYJhXvHSN5yIBFDJNxujelyZoPfyRRZdUt4v9+zvUQboqFLRH1zzUCAwEAAaOC
            A0swggNHMIHmBgNVHREEgd4wgduCFSoudnMucmMuZGVtby5pbnRlcm5hbIIWKi52
            czIucmMuZGVtby5pbnRlcm5hbIIWKi52czMucmMuZGVtby5pbnRlcm5hbIIWKi52
            czQucmMuZGVtby5pbnRlcm5hbIIWKi52czUucmMuZGVtby5pbnRlcm5hbIIXKi5n
            c2xiLnJjLmRlbW8uaW50ZXJuYWyCFiouYWtvLnJjLmRlbW8uaW50ZXJuYWyCFyou
            YWtvMi5yYy5kZW1vLmludGVybmFsghgqLmdzbGIyLnJjLmRlbW8uaW50ZXJuYWww
            HQYDVR0OBBYEFLfyI1CueHW1Ni/PyLHg5RWM+DMeMB8GA1UdIwQYMBaAFJBUB37l
            U+Y0CD5d+Nm2lN+tGSfbMIHUBgNVHR8EgcwwgckwgcaggcOggcCGgb1sZGFwOi8v
            L0NOPVJDLUxBQi1DQSxDTj1yYy13aW5zZXJ2ZXIsQ049Q0RQLENOPVB1YmxpYyUy
            MEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9
            cmMsREM9ZGVtbyxEQz1pbnRlcm5hbD9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0
            P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnQwgcMGCCsGAQUF
            BwEBBIG2MIGzMIGwBggrBgEFBQcwAoaBo2xkYXA6Ly8vQ049UkMtTEFCLUNBLENO
            PUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1D
            b25maWd1cmF0aW9uLERDPXJjLERDPWRlbW8sREM9aW50ZXJuYWw/Y0FDZXJ0aWZp
            Y2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwDgYD
            VR0PAQH/BAQDAgWgMD0GCSsGAQQBgjcVBwQwMC4GJisGAQQBgjcVCIT+omSHs+kd
            hrWFLYHV9T6Dnd5RRYfd4hCHyJZyAgFkAgEEMBMGA1UdJQQMMAoGCCsGAQUFBwMB
            MBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYBBQUHAwEwCgYIKoZIzj0EAwIDSQAwRgIh
            AMhfShgzg24rQOdY9TWid+pq8mg88VbwzCISNQue+sv+AiEAj9mfL07GQkXDGr7e
            PaI8cGK8L85mroSzX2e1UcEh/TQ=
            -----END CERTIFICATE-----
        key_params:
          algorithm: "SSL_KEY_ALGORITHM_RSA"
          rsa_params:
            key_size: "SSL_KEY_2048_BITS"
            exponent: 65537
        key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCprx4lmK4GcXyN
          FNoblUIcLY0ea4+KmDisbbXc7cE+DTlbWnr93tKDKOyD93ePSSNt+p7X4Yaaphjk
          BsB5p+ZwM1OFlUHMBdrAq0WwHCYigICjmpjObuEp1JZGmYYlkW+H+0cq9FHbyNjH
          6HciBfl7wB7Mlw/SzXC74UazkbpisRf4CBWAPA9tRM+xFf0HvOURRM1R2+Zh53qE
          ABS45DcIb9o9z1motMXE3X6xhdDenvY89dRmvErjz0ej+vpu1LFO6I0nLfBe32L5
          P9wneAWpUUVFIzocu32r2CYV7x0jeciARQyTcbo3pcmaD38kUWXVLeL/fs71EG6K
          hS0R9c81AgMBAAECggEAJoVo1KQqra/J1MVtFmH2FiuJI+TLO21/QDXP2Y3oFswt
          vz11OnkBVWFPAE6Hx/GUp30D3oKGaklW0T1vKK8jM0mTpnnR7B1QIfk/4tEhHygJ
          DBsmoYauey6VxwVHXPP9W+OBrpC0nK6l+AwgL4snrh5ZX5zTrMmS1DQ6Nr3YkFrB
          MhedkWsCNqSgbdKKEdlPwoDsbw0UVYdAxKevJj5wDEi+2OVHDZDsSHaA4YKAjT4H
          ykqF1dmZhCT26lJDKWADd/iUUafVGHw2hGRveNQDhhb0zM6AeWkonsKbzRNIwuda
          WTkYtXHstBOQKMOz9TzUij3liNtr2mHqTvOrZIr+QQKBgQDRzI+SCLroYkMnhTZ4
          y490t3UyKKciikTAkBZ4GSGRGX57blvbkk3r1npTabs3e6ZLPShqEt506pPniVAC
          zoZELRQdG8u+5L03IhaZmj9JQIl3+79w4BvF4Cgf88/+1awGY0KV1ecvW7nyD9eR
          8aZkT5MLUBf3lT5s916B86XuLQKBgQDPDRHmLjqTy3cXP+KL+KtdFSUSinddfKd4
          ZazFyJTfocZVmAJgi+ORQtLrjAJQKN8vNZW7iVHsLKvjb/U9bCZscbO9eF4enPi4
          cUgYt8PlonLjn/xIkTfKGtnt+ws694ce6ndVEy9Pdjm/26R85DE4qvhY3ATsZ3bM
          mRIMieGSKQKBgQC4VVF37++5KkzytlrL+57J4D86mPlwoagSwQbc8sfJY2r8LFTN
          MVkBc+r6yxVRhHTx+oQ93uJSO6FEeCMytB7IXAsmIDv+N6AAhxTwVNRyGiAuqaTl
          GiOM0oyutlvz/e0tl5zzZYPA2okgI8c2VenqjPgXooHMaPb2aspAx8Ds6QKBgCPR
          9QjHcqbjCmVhTgY9LRhbciB1CBWKXUa9AFjvTKIr0K46MB8X1HTrBKZvgG7xwzrd
          oFvjc+LSD6K3WcwYi8UzHo9m5ZGSQo1WO8za7e8qXYn3waOkS+yRHKbJSbYX4K5+
          jcqQGR08LN1+WESrDcDqAzEMT2W+uJTI3pCAwh+RAoGAYQ3szgjp1Oq93AXTQpXh
          WaMbtxIm232duK18t0s+ruNg6pP/ntmO2DF+kGaTZeFNyterlsgRvlpZYojaP2bG
          RwegvGuRd6h3SrNpXQQwM9NlbzVQ3cCCI8gYSZjn7NqWKxlvYvqOsViw2rQvCPqh
          KjFLQT8fnVtRcOzSb2D+YE0=
          -----END PRIVATE KEY-----
        format: SSL_PEM

    - name: "Create Wildcard-RSA-Cert-Portal"
      vmware.alb.avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "Wildcard-RSA-Cert-Portal"
        type: "SSL_CERTIFICATE_TYPE_SYSTEM"
        certificate:
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIE4zCCBIigAwIBAgITGAAAAAjHUd9Hpl7AegAAAAAACDAKBggqhkjOPQQDAjBY
            MRgwFgYKCZImiZPyLGQBGRYIaW50ZXJuYWwxFDASBgoJkiaJk/IsZAEZFgRkZW1v
            MRIwEAYKCZImiZPyLGQBGRYCcmMxEjAQBgNVBAMTCVJDLUxBQi1DQTAeFw0yNDEw
            MjExNzU1NThaFw0yNjEwMjExNzU1NThaMDsxCzAJBgNVBAYTAkdCMQ8wDQYDVQQK
            EwZSQ0RFTU8xGzAZBgNVBAMMEioucmMuZGVtby5pbnRlcm5hbDCCASIwDQYJKoZI
            hvcNAQEBBQADggEPADCCAQoCggEBAOCF/oNSUG00CEJhCMZDVqKzHPYua52UT/pp
            iQm7RYUvMAjTV8MFvB0B/tWSNejEEUu1ux/SDpekTBQ0jWRCY9rhfWWug5Jvc2YF
            jMnr/it8u0A+bZ6RsK6DsS3laSlXkJEorjmmP0bKTrYFbjOW7fL2UW8vy4mLcN2S
            aURsw4/8XxTggxgdQIJK82Ep8awRc+HxjEFhpUvu5FLJ1wz5HZi6t8LhE4A9btrA
            wgxbAE1qF6O8hDZpAwGI7pbj08Rb3BMlzvqQwUWQ5Dy682QY5uDQ3SVCaaadPvLs
            9DxYtLUSNHxEvFOKC6xK7xZekgdALu7ES/4U+Xx6z0m425FZAG0CAwEAAaOCAoEw
            ggJ9MB0GA1UdEQQWMBSCEioucmMuZGVtby5pbnRlcm5hbDAdBgNVHQ4EFgQUiMOp
            Q8EQ1oKxdvZCWswuhgsmvFYwHwYDVR0jBBgwFoAUkFQHfuVT5jQIPl342baU360Z
            J9swgdQGA1UdHwSBzDCByTCBxqCBw6CBwIaBvWxkYXA6Ly8vQ049UkMtTEFCLUNB
            LENOPXJjLXdpbnNlcnZlcixDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2Vydmlj
            ZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1yYyxEQz1kZW1vLERD
            PWludGVybmFsP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RD
            bGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludDCBwwYIKwYBBQUHAQEEgbYwgbMwgbAG
            CCsGAQUFBzAChoGjbGRhcDovLy9DTj1SQy1MQUItQ0EsQ049QUlBLENOPVB1Ymxp
            YyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24s
            REM9cmMsREM9ZGVtbyxEQz1pbnRlcm5hbD9jQUNlcnRpZmljYXRlP2Jhc2U/b2Jq
            ZWN0Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0eTAOBgNVHQ8BAf8EBAMCBaAw
            PQYJKwYBBAGCNxUHBDAwLgYmKwYBBAGCNxUIhP6iZIez6R2GtYUtgdX1PoOd3lFF
            h93iEIfIlnICAWQCAQQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwGwYJKwYBBAGCNxUK
            BA4wDDAKBggrBgEFBQcDATAKBggqhkjOPQQDAgNJADBGAiEAnDlPLsVyZpSuFJPm
            55bK6f2MJ6KodE3w7gY/6JUcrooCIQCtxG0TD5fKGRfLbovgy5KTSryHhz5zWqaB
            PyKyfRc9ww==
            -----END CERTIFICATE-----
        key_params:
          algorithm: "SSL_KEY_ALGORITHM_RSA"
          rsa_params:
            key_size: "SSL_KEY_2048_BITS"
            exponent: 65537
        key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDghf6DUlBtNAhC
          YQjGQ1aisxz2LmudlE/6aYkJu0WFLzAI01fDBbwdAf7VkjXoxBFLtbsf0g6XpEwU
          NI1kQmPa4X1lroOSb3NmBYzJ6/4rfLtAPm2ekbCug7Et5WkpV5CRKK45pj9Gyk62
          BW4zlu3y9lFvL8uJi3DdkmlEbMOP/F8U4IMYHUCCSvNhKfGsEXPh8YxBYaVL7uRS
          ydcM+R2YurfC4ROAPW7awMIMWwBNahejvIQ2aQMBiO6W49PEW9wTJc76kMFFkOQ8
          uvNkGObg0N0lQmmmnT7y7PQ8WLS1EjR8RLxTigusSu8WXpIHQC7uxEv+FPl8es9J
          uNuRWQBtAgMBAAECggEARxLjsJp8DzWrb6fb6Tcj07kzb9LeCjIK51BFKyl3JmP7
          pq+QVpIYLG6XRvBT1G1MtFTA+Z+7MtG1q6e/In/JsF41Hd0SlWZmd2NGYB0uhoGj
          nQCmHs4ryfKyQb8ffRDVGL5x+Jnh6fzc0c4CRp5+kKzctn/AxLe5cMqKPDjZ51f6
          w/LvNAiE1FY+kdz5R3oG0W5O6niEjWgZzsheWzuPPHJ5ZVlYF3evIf/PwEQGiGJT
          upaBQmdcpS95BiZmJIUxwj2INi5SB7j8jLDula8PPP825uybsVYMXNSG/C/PK+vF
          H5ec1wHkHjV0NYUWuL15i7QevE0Pd8m7vKbvlSwi2QKBgQD1vh/vJjqgLu/DA5R0
          E1MXTgJKqY8ZnjNxshIEbf5GRvbYFN7ZTg4WXMwCpuI+C0aDT3HT6YiNkV+AR/lW
          84mfcPYusA1ByIQLyuRznLRzWC+2byquMkWW+zKAKsOhC/U52YzrjrSbFxCf3aDe
          BkGWUfjPj98Cc+2U7utjqUtzBwKBgQDp5SG6CbqiiUR/UFYyyaRlLEqqJnoIT5Jw
          sSCyRWtMsd7Zr069lFaBKuw2LXoOljxn0idyw2E/dRilcmMw8JEz+l/eb/7E75mD
          2PR+XVMQyl63Ij5+/ZA5o8IB8Ssccyb8a5/Yru8eARUQIQIP791TIBGrRFUQXmWM
          m0gfVJ8P6wKBgQDNbRcC8uE1QKdbTWXPNsxSAfs2cNHYJ4B3vdUD8PMLyozVC3VT
          EMYD+aTtXpZoKULTyBiufl2RgoHkGcac4k8cgvC5DKC4aifAN+aLoubSOVkBV6LF
          Je84jFql+5m3yehAaNU9oPjnYPubuEie8XnocDPfRzS0tzZXNvZ9RGt3BwKBgBui
          TbTMN3fCngwosrZ3amvlqsCloR9gP13/H2zQlNfP4BN6CeSOJRZHuva/sr8McwCV
          LMH7YX7817ecZym+EnnAqBkAxGoCIPIZ7PENF6ZRMpWSfy3DyYl11pMiKkTHOiDy
          mkUgjfHOkO2B6Nt3LIAItu20OhSgAoF1SzUga1aXAoGAWCXptwYWMKLPFWwZj/ql
          GUuh3EgV8BDXcabhxKO8fMYDIStJE/t5N4jtWJLpizrVLXl0b9lHAIzL41Xpzmi/
          Wc7uv2JFKJcHX3fzgoY2+8ZT3DUofRrsyqylSXz8hckx/3xMMsRWsEMKbHhD8ZeH
          MESoXuoE2cyZVsewzHniWtI=
          -----END PRIVATE KEY-----
        format: SSL_PEM

    - name: "Create Wildcard-ECDSA-Cert-Portal"
      vmware.alb.avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "Wildcard-ECDSA-Cert-Portal"
        type: "SSL_CERTIFICATE_TYPE_SYSTEM"
        certificate:
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIENTCCA9qgAwIBAgITGAAAAAfgW85UXa+e3AAAAAAABzAKBggqhkjOPQQDAjBY
            MRgwFgYKCZImiZPyLGQBGRYIaW50ZXJuYWwxFDASBgoJkiaJk/IsZAEZFgRkZW1v
            MRIwEAYKCZImiZPyLGQBGRYCcmMxEjAQBgNVBAMTCVJDLUxBQi1DQTAeFw0yNDEw
            MjExNzU0MTNaFw0yNjEwMjExNzU0MTNaMDsxCzAJBgNVBAYTAkdCMQ8wDQYDVQQK
            EwZSQ0RFTU8xGzAZBgNVBAMMEioucmMuZGVtby5pbnRlcm5hbDB2MBAGByqGSM49
            AgEGBSuBBAAiA2IABKfmXbp3xbL30W3DJ1hLBeTX1VHjijeDCdeEIkPYFThsEnsp
            PxLIHxMJJkWBCrQuSVLDcEh4dUUzvvx90UxDRwzxrn4NNYX3cmcMWdflhRmAel6J
            uzYCw0fT5RxSa3JDGqOCAoEwggJ9MB0GA1UdEQQWMBSCEioucmMuZGVtby5pbnRl
            cm5hbDAdBgNVHQ4EFgQU6MDaNWT5v+0c52Lo0qlFFtO0aEowHwYDVR0jBBgwFoAU
            kFQHfuVT5jQIPl342baU360ZJ9swgdQGA1UdHwSBzDCByTCBxqCBw6CBwIaBvWxk
            YXA6Ly8vQ049UkMtTEFCLUNBLENOPXJjLXdpbnNlcnZlcixDTj1DRFAsQ049UHVi
            bGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlv
            bixEQz1yYyxEQz1kZW1vLERDPWludGVybmFsP2NlcnRpZmljYXRlUmV2b2NhdGlv
            bkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludDCBwwYI
            KwYBBQUHAQEEgbYwgbMwgbAGCCsGAQUFBzAChoGjbGRhcDovLy9DTj1SQy1MQUIt
            Q0EsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2Vz
            LENOPUNvbmZpZ3VyYXRpb24sREM9cmMsREM9ZGVtbyxEQz1pbnRlcm5hbD9jQUNl
            cnRpZmljYXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0
            eTAOBgNVHQ8BAf8EBAMCB4AwPQYJKwYBBAGCNxUHBDAwLgYmKwYBBAGCNxUIhP6i
            ZIez6R2GtYUtgdX1PoOd3lFFh93iEIfIlnICAWQCAQQwEwYDVR0lBAwwCgYIKwYB
            BQUHAwEwGwYJKwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDATAKBggqhkjOPQQDAgNJ
            ADBGAiEAs4aUGV8FAkAYm86xN0LyPM46mmdr1jHN+ygjk3UiP4YCIQD/4WQo3L2G
            YvzUNwIZroly7hIoqIoYJ9tF4zKXiBkjWQ==
            -----END CERTIFICATE-----
        key_params:
          algorithm: "SSL_KEY_ALGORITHM_EC"
          ec_params:
            curve: "SSL_KEY_EC_CURVE_SECP256R1"
        key: |
            -----BEGIN EC PRIVATE KEY-----
            MIGkAgEBBDArB4kFkLNZjfrEjvww6EAYEbKV3cX6KXydkC3pJ31amJK3Ef8/nl25
            uoFWxD01FpegBwYFK4EEACKhZANiAASn5l26d8Wy99FtwydYSwXk19VR44o3gwnX
            hCJD2BU4bBJ7KT8SyB8TCSZFgQq0LklSw3BIeHVFM778fdFMQ0cM8a5+DTWF93Jn
            DFnX5YUZgHpeibs2AsNH0+UcUmtyQxo=
            -----END EC PRIVATE KEY-----
        format: SSL_PEM
