---
- name: "Configure SSL Certificates"
  hosts: "localhost"
  connection: "local"
  vars_files:
    - "generic.yml"

  tasks:
    - name: "Create RC-LABCA-ECDSA Certificate"
      vmware.alb.avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "RC-LABCA-ECDSA"
        type: "SSL_CERTIFICATE_TYPE_CA"
        certificate:
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIICLTCCAdOgAwIBAgIQGXp37KqZ6rFIfgLPJKD7wDAKBggqhkjOPQQDAjBvMRUw
            EwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNhdmkxFDASBgoJ
            kiaJk/IsZAEZFgRkZW1vMRIwEAYKCZImiZPyLGQBGRYCcmMxFzAVBgNVBAMTDlJD
            LUxBQkNBLUVDRFNBMB4XDTE4MDEwMzE0NDE1NloXDTQzMDEwMzE0NTE1NVowbzEV
            MBMGCgmSJomT8ixkARkWBWxvY2FsMRMwEQYKCZImiZPyLGQBGRYDYXZpMRQwEgYK
            CZImiZPyLGQBGRYEZGVtbzESMBAGCgmSJomT8ixkARkWAnJjMRcwFQYDVQQDEw5S
            Qy1MQUJDQS1FQ0RTQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEp+rNLyOFAt
            eLVu3hexDWGxDJ0WV3ssUm/jfTn9o3usQgWTMRONI1/lgF8fKKiRwQW1lSfLaabK
            h6hNqdEgWRyjUTBPMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1Ud
            DgQWBBS4VEYluU4PBzDVkVLupZlIJxxZMDAQBgkrBgEEAYI3FQEEAwIBADAKBggq
            hkjOPQQDAgNIADBFAiEA3iqwIFGDfIklwC+IVhdtWezcb6fMTrBMOuCibwFWhaAC
            IGokgObFqzqetbZiPubvJlUwnWQPwhYDRXuqxTTpnfGv
            -----END CERTIFICATE-----
        key_params:
          algorithm: "SSL_KEY_ALGORITHM_EC"
          ec_params:
            curve: "SSL_KEY_EC_CURVE_SECP256R1"
        format: SSL_PEM

    - name: "Create Wildcard-ECDSA-Cert"
      vmware.alb.avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "Wildcard-ECDSA-Cert"
        type: "SSL_CERTIFICATE_TYPE_VIRTUALSERVICE"
        certificate:
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIFLzCCBNWgAwIBAgITVwAAAG6/pTSR6KL7igAAAAAAbjAKBggqhkjOPQQDAjBv
            MRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNhdmkxFDAS
            BgoJkiaJk/IsZAEZFgRkZW1vMRIwEAYKCZImiZPyLGQBGRYCcmMxFzAVBgNVBAMT
            DlJDLUxBQkNBLUVDRFNBMB4XDTIzMDEwMzE1MDk0MVoXDTI1MDEwMjE1MDk0MVow
            XzELMAkGA1UEBhMCR0IxDzANBgNVBAoTBlZNd2FyZTEcMBoGA1UEAwwTKi5yYy5k
            ZW1vLmF2aS5sb2NhbDEhMB8GCSqGSIb3DQEJARYScmNhc3VsYUB2bXdhcmUuY29t
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBKZ8f4U3LeFI/Fl2VmmKSYo58P+4
            cZ+RU8XX7UMd+4mRZsRmmHwUtSZpfU5dbSzm0JrkXFVos8B2Frf4w7XVi6OCA14w
            ggNaMIIBHwYDVR0RBIIBFjCCARKCEyoucmMuZGVtby5hdmkubG9jYWyCFioudnMu
            cmMuZGVtby5hdmkubG9jYWyCFyoudnMyLnJjLmRlbW8uYXZpLmxvY2FsghcqLnZz
            My5yYy5kZW1vLmF2aS5sb2NhbIIXKi52czQucmMuZGVtby5hdmkubG9jYWyCFyou
            dnM1LnJjLmRlbW8uYXZpLmxvY2FsghcqLnZzNi5yYy5kZW1vLmF2aS5sb2NhbIIY
            Ki5nc2xiLnJjLmRlbW8uYXZpLmxvY2FsghcqLms4cy5yYy5kZW1vLmF2aS5sb2Nh
            bIIYKi5rOHMyLnJjLmRlbW8uYXZpLmxvY2FsghkqLmdzbGIyLnJjLmRlbW8uYXZp
            LmxvY2FsMB0GA1UdDgQWBBRORPP275YNx3K3CkBmURGggb3pRDAfBgNVHSMEGDAW
            gBS4VEYluU4PBzDVkVLupZlIJxxZMDCB3QYDVR0fBIHVMIHSMIHPoIHMoIHJhoHG
            bGRhcDovLy9DTj1SQy1MQUJDQS1FQ0RTQSxDTj1yYy13aW5zZXJ2ZXIsQ049Q0RQ
            LENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZp
            Z3VyYXRpb24sREM9cmMsREM9ZGVtbyxEQz1hdmksREM9bG9jYWw/Y2VydGlmaWNh
            dGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlv
            blBvaW50MIHMBggrBgEFBQcBAQSBvzCBvDCBuQYIKwYBBQUHMAKGgaxsZGFwOi8v
            L0NOPVJDLUxBQkNBLUVDRFNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2
            aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPXJjLERDPWRlbW8s
            REM9YXZpLERDPWxvY2FsP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1j
            ZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MCEGCSsGAQQBgjcUAgQUHhIAVwBlAGIAUwBl
            AHIAdgBlAHIwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAoG
            CCqGSM49BAMCA0gAMEUCIFZH1BWezoZIgFB6uXk1cHonJSqrJ7foDnbdH4TEX9dN
            AiEAlv4UfhFl2b0dgJ4z4AAfeN19M5ScUV9Y/esjw+b4osQ=
            -----END CERTIFICATE-----
        key_params:
          algorithm: "SSL_KEY_ALGORITHM_EC"
          ec_params:
            curve: "SSL_KEY_EC_CURVE_SECP256R1"
        key: |
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIFw7ywq2MV15LS4qGXWltOwuK+RWZghIZAX2UcaWFkR8oAoGCCqGSM49
          AwEHoUQDQgAEBKZ8f4U3LeFI/Fl2VmmKSYo58P+4cZ+RU8XX7UMd+4mRZsRmmHwU
          tSZpfU5dbSzm0JrkXFVos8B2Frf4w7XViw==
          -----END EC PRIVATE KEY-----
        format: SSL_PEM

    - name: "Create Wildcard-RSA-Cert"
      vmware.alb.avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "Wildcard-RSA-Cert"
        type: "SSL_CERTIFICATE_TYPE_VIRTUALSERVICE"
        certificate:
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIF+jCCBaCgAwIBAgITVwAAAG1kN6x3T3cqJAAAAAAAbTAKBggqhkjOPQQDAjBv
            MRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNhdmkxFDAS
            BgoJkiaJk/IsZAEZFgRkZW1vMRIwEAYKCZImiZPyLGQBGRYCcmMxFzAVBgNVBAMT
            DlJDLUxBQkNBLUVDRFNBMB4XDTIzMDEwMzE1MDgzNFoXDTI1MDEwMjE1MDgzNFow
            XzELMAkGA1UEBhMCR0IxDzANBgNVBAoTBlZNd2FyZTEcMBoGA1UEAwwTKi5yYy5k
            ZW1vLmF2aS5sb2NhbDEhMB8GCSqGSIb3DQEJARYScmNhc3VsYUB2bXdhcmUuY29t
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwsv/YZvqV6mzRqNBtWxH
            N0tIS/Iqv725Z3+ppOVG38opnVNtNp+jy/MCyxYxLCnUx8f3Aix/KuFS8Cs/SS/0
            pv0ndQu1q4+XDqrNez5ggJHypoHmZwxO3o1TlFHZddbmaL5D9w6bcO3fFAVRorh9
            dHXYdMLpatm638H2JSeAV03hNa1QxfUoeisymwSr4qH8zEfM1V0OJdeU3ePMcyjQ
            J0bFlrNLmYGBDwR6VgH1k7o9nqK/ANwnSiqZeaYc6xPGEtWt0J+EEPjS4C2CtU3r
            vblfyp5SPOBbLPKjRTmfd9ASJXfcCshLr6RXr4zt+OrGKIN2hTm2IhECQyWOHhD4
            SQIDAQABo4IDXjCCA1owggEfBgNVHREEggEWMIIBEoITKi5yYy5kZW1vLmF2aS5s
            b2NhbIIWKi52cy5yYy5kZW1vLmF2aS5sb2NhbIIXKi52czIucmMuZGVtby5hdmku
            bG9jYWyCFyoudnMzLnJjLmRlbW8uYXZpLmxvY2FsghcqLnZzNC5yYy5kZW1vLmF2
            aS5sb2NhbIIXKi52czUucmMuZGVtby5hdmkubG9jYWyCFyoudnM2LnJjLmRlbW8u
            YXZpLmxvY2FsghgqLmdzbGIucmMuZGVtby5hdmkubG9jYWyCFyouazhzLnJjLmRl
            bW8uYXZpLmxvY2FsghgqLms4czIucmMuZGVtby5hdmkubG9jYWyCGSouZ3NsYjIu
            cmMuZGVtby5hdmkubG9jYWwwHQYDVR0OBBYEFNk9UTuS6UBfYIAWNBLF2iH66DzC
            MB8GA1UdIwQYMBaAFLhURiW5Tg8HMNWRUu6lmUgnHFkwMIHdBgNVHR8EgdUwgdIw
            gc+ggcyggcmGgcZsZGFwOi8vL0NOPVJDLUxBQkNBLUVDRFNBLENOPXJjLXdpbnNl
            cnZlcixDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2Vydmlj
            ZXMsQ049Q29uZmlndXJhdGlvbixEQz1yYyxEQz1kZW1vLERDPWF2aSxEQz1sb2Nh
            bD9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JM
            RGlzdHJpYnV0aW9uUG9pbnQwgcwGCCsGAQUFBwEBBIG/MIG8MIG5BggrBgEFBQcw
            AoaBrGxkYXA6Ly8vQ049UkMtTEFCQ0EtRUNEU0EsQ049QUlBLENOPVB1YmxpYyUy
            MEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9
            cmMsREM9ZGVtbyxEQz1hdmksREM9bG9jYWw/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29i
            amVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwIQYJKwYBBAGCNxQCBBQe
            EgBXAGUAYgBTAGUAcgB2AGUAcjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYI
            KwYBBQUHAwEwCgYIKoZIzj0EAwIDSAAwRQIhANECu5RVAum94X6s7Os7VYPcbDI3
            lqwtBxQ5kL1ibm10AiA8xaWYOuhDLWYIv9dDEjZ1TOAmBjR7HMF6IjOlaMW9eQ==
            -----END CERTIFICATE-----
        key_params:
          algorithm: "SSL_KEY_ALGORITHM_RSA"
          rsa_params:
            key_size: "SSL_KEY_2048_BITS"
            exponent: 65537
        key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDCy/9hm+pXqbNG
          o0G1bEc3S0hL8iq/vblnf6mk5UbfyimdU202n6PL8wLLFjEsKdTHx/cCLH8q4VLw
          Kz9JL/Sm/Sd1C7Wrj5cOqs17PmCAkfKmgeZnDE7ejVOUUdl11uZovkP3Dptw7d8U
          BVGiuH10ddh0wulq2brfwfYlJ4BXTeE1rVDF9Sh6KzKbBKviofzMR8zVXQ4l15Td
          48xzKNAnRsWWs0uZgYEPBHpWAfWTuj2eor8A3CdKKpl5phzrE8YS1a3Qn4QQ+NLg
          LYK1Teu9uV/KnlI84Fss8qNFOZ930BIld9wKyEuvpFevjO346sYog3aFObYiEQJD
          JY4eEPhJAgMBAAECggEAVicU/t2PSlAimvYvZIbMBHeGNRiYsY6+hjjfFa/Vpbpq
          p0szfTojnlsO/DUHcGnb0rPs2ghGAff/z3rBFaRhBs3l+o1APu1VuMXv9TcERTjH
          Yb8H4MF/zEwjD/EXRVfTNbYYpxbNxqddxyQHE/mWesB4CEQAKiK71KSbMZmD2Jgy
          nDgDOor0VdDLdaz7o1BBzEHGNWnt8LMSWO2MtBStn+sE6Wz5ktr0Kaa1Wddyi5j5
          Q350sbLz98HIY2BmT3iznyRQpWGDayuBKfSh02qZFyB0WbGiuvFR57AM3jg/qHjr
          x7mw9IyMcdihM4t41C+Mk8/q9uSvXjSr1lTZZOGlkQKBgQDh/U+t2kD8R3sblRFS
          sVjGBtotTtbp2Dg5sh0Nib9hZY+ldfEpg6nPcVimJsr/Qp1HkMYCHS5OON5ewQP8
          QfbdQGK7bERkfhw7aEXco24AT87j9tVaKN8zZ5ltWlSu/4diiTIqD3yWJaaw4MP3
          2D7Ss1yKA7MdMCHCpK9lO5tk7QKBgQDcqkTAlUDIGK0O3fRli8yAwO12551ZfmS+
          3ApiuZmbFr7hssgGMeOJnlo4P3V0gF6RT3qTW/Vfp412X0fAO3Ys24duNC8YyNgw
          uEjE3ftmnSU/pwqdXecXz6WsrB1DWCyG3u7lSRW8Y6ibOi2VNyVr9dmOX+DcGM31
          sZ8L0gNxTQKBgB28569I+SQ5g8mtZAotrDDi1fMAXOeIvF1bQtd1OOnoI27yhjmg
          ScgycifrEutkKK4yLtw4Ws+QTDLL02pug725q0ReiuFuduiaYBcYqnEAD4mQAaNL
          nZN2Hop1SI9+sKIWy7MdNpfLfJPp/9+tZRb040iGFBvTKZ4jbbE0ls5BAoGASyN/
          fcRU5s3gP+u8SMetvznyokaEAfFUBNmQf8WLVJAON3RVQCbEwBu3xOd261C64ugZ
          aQwrJYM8XE5ddEvLFcM6/n+uedYKJ6zYupCMBokEIgSTTLqo8ia213FUFZZ0swg+
          eLzGNfwJcbIBy4mXqIdyqVRkkQ2xNDRjX/cHTRECgYB3bAnDTVegKFtzv1OIQPiS
          rqFHJGJyffTrYfMTlhH6z4ZxOY33cuB0YYoA3tbzZx9E/Z2iVBCcAu9yy2il6auh
          kQuZXUBCk3vkBCebNcOAP/NYUQRKBh7Tnmj/f/sTwjsbFa97T00nn/ptxm5IrO1z
          Lg/Z9xDKD9+ji9Ulxyb1Uw==
          -----END PRIVATE KEY-----
        format: SSL_PEM

    - name: "Create Wildcard-ECDSA-Cert-Portal"
      vmware.alb.avi_sslkeyandcertificate:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "Wildcard-ECDSA-Cert-Portal"
        type: "SSL_CERTIFICATE_TYPE_SYSTEM"
        certificate:
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIFLzCCBNWgAwIBAgITVwAAAG6/pTSR6KL7igAAAAAAbjAKBggqhkjOPQQDAjBv
            MRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNhdmkxFDAS
            BgoJkiaJk/IsZAEZFgRkZW1vMRIwEAYKCZImiZPyLGQBGRYCcmMxFzAVBgNVBAMT
            DlJDLUxBQkNBLUVDRFNBMB4XDTIzMDEwMzE1MDk0MVoXDTI1MDEwMjE1MDk0MVow
            XzELMAkGA1UEBhMCR0IxDzANBgNVBAoTBlZNd2FyZTEcMBoGA1UEAwwTKi5yYy5k
            ZW1vLmF2aS5sb2NhbDEhMB8GCSqGSIb3DQEJARYScmNhc3VsYUB2bXdhcmUuY29t
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBKZ8f4U3LeFI/Fl2VmmKSYo58P+4
            cZ+RU8XX7UMd+4mRZsRmmHwUtSZpfU5dbSzm0JrkXFVos8B2Frf4w7XVi6OCA14w
            ggNaMIIBHwYDVR0RBIIBFjCCARKCEyoucmMuZGVtby5hdmkubG9jYWyCFioudnMu
            cmMuZGVtby5hdmkubG9jYWyCFyoudnMyLnJjLmRlbW8uYXZpLmxvY2FsghcqLnZz
            My5yYy5kZW1vLmF2aS5sb2NhbIIXKi52czQucmMuZGVtby5hdmkubG9jYWyCFyou
            dnM1LnJjLmRlbW8uYXZpLmxvY2FsghcqLnZzNi5yYy5kZW1vLmF2aS5sb2NhbIIY
            Ki5nc2xiLnJjLmRlbW8uYXZpLmxvY2FsghcqLms4cy5yYy5kZW1vLmF2aS5sb2Nh
            bIIYKi5rOHMyLnJjLmRlbW8uYXZpLmxvY2FsghkqLmdzbGIyLnJjLmRlbW8uYXZp
            LmxvY2FsMB0GA1UdDgQWBBRORPP275YNx3K3CkBmURGggb3pRDAfBgNVHSMEGDAW
            gBS4VEYluU4PBzDVkVLupZlIJxxZMDCB3QYDVR0fBIHVMIHSMIHPoIHMoIHJhoHG
            bGRhcDovLy9DTj1SQy1MQUJDQS1FQ0RTQSxDTj1yYy13aW5zZXJ2ZXIsQ049Q0RQ
            LENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZp
            Z3VyYXRpb24sREM9cmMsREM9ZGVtbyxEQz1hdmksREM9bG9jYWw/Y2VydGlmaWNh
            dGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlv
            blBvaW50MIHMBggrBgEFBQcBAQSBvzCBvDCBuQYIKwYBBQUHMAKGgaxsZGFwOi8v
            L0NOPVJDLUxBQkNBLUVDRFNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2
            aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPXJjLERDPWRlbW8s
            REM9YXZpLERDPWxvY2FsP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1j
            ZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MCEGCSsGAQQBgjcUAgQUHhIAVwBlAGIAUwBl
            AHIAdgBlAHIwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAoG
            CCqGSM49BAMCA0gAMEUCIFZH1BWezoZIgFB6uXk1cHonJSqrJ7foDnbdH4TEX9dN
            AiEAlv4UfhFl2b0dgJ4z4AAfeN19M5ScUV9Y/esjw+b4osQ=
            -----END CERTIFICATE-----
        key_params:
          algorithm: "SSL_KEY_ALGORITHM_EC"
          ec_params:
            curve: "SSL_KEY_EC_CURVE_SECP256R1"
        key: |
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIFw7ywq2MV15LS4qGXWltOwuK+RWZghIZAX2UcaWFkR8oAoGCCqGSM49
          AwEHoUQDQgAEBKZ8f4U3LeFI/Fl2VmmKSYo58P+4cZ+RU8XX7UMd+4mRZsRmmHwU
          tSZpfU5dbSzm0JrkXFVos8B2Frf4w7XViw==
          -----END EC PRIVATE KEY-----
        format: SSL_PEM
