---
- name: "Modify a Pool Member"
  hosts: "localhost"
  connection: "local"
  vars_files:
    - '{{ "site_" + deployment_site + ".yml" }}'
  tasks:
    - name: Update Pool State | Remove Server
      vmware.alb.avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: rc-demo-pool
        avi_api_update_method: patch
        avi_api_patch_op: delete
        servers:
          - ip:
              addr: 0.0.0.0
              type: V4
            hostname: rc-linux-03.rc.demo.avi.local
            resolve_server_by_dns: true
