# code: language=ansible
---
build_location: "builds"
controller_version: "30.2.1"
build_name: "last-built "
controller_num_cpu: 8
controller_mem: 32
controller_disk: 160
# manual_image_path: "/mnt/files/yvsn42/controller.ova"
