# code: language=ansible
---
gslb_sites:
  "London":
    controller_address: "10.6.248.91"
    dns_services:
      - name: "dns1.rc.demo.internal"
        # domain_names:
        #   - "gslb.rc.demo.internal"
    type: "GSLB_ACTIVE_MEMBER"
  "Amsterdam":
    controller_address: "10.6.248.92"
    dns_services:
      - name: "dns2.rc.demo.internal"
    type: "GSLB_ACTIVE_MEMBER"
  "Paris":
    controller_address: "10.6.248.93"
    dns_services:
      - name: "dns3.rc.demo.internal"
    type: "GSLB_ACTIVE_MEMBER"

gslb_leader_site: "London"

gslb_dns_domains:
  - domain_name: "gslb.rc.demo.internal"
  - domain_name: "gslb2.rc.demo.internal"

gslb_account:
  name: "gslbadmin"
  password: "{{ gslb_admin_password }}"
  api_version: "30.2.2"

gslb_service:
  name: "rc-demo-gslb"
  fqdns:
    - "rc-demo-gslb.gslb.rc.demo.internal"
  groups:
    - name: "rc-demo-gslb-pool-1"
      algorithm: "GSLB_ALGORITHM_ROUND_ROBIN"
      members:
        - vs_name: "rc-demo"
          site_name: "London"
        - vs_name: "rc-demo"
          site_name: "Amsterdam"
        - vs_name: "rc-demo"
          site_name: "Paris"
